### ISSUE TITLE
[DevOps] Create GCP Project and share access

### ISSUE THREAD

**Issue by MiguelABFlores** [MiguelABFlores/vet-services-website#1]
### Overall Task
Creating resources and sharing access is essential to a project developed by a team.

### Tasks:

- [x] Create Project in GCP
- [x] Ask John for his google account
- [x] Share access to the project
